# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Programs\mingw64\bin\cmake.exe

# The command to remove a file.
RM = D:\Programs\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\WangCJ\Codes\Dev Codes\OITools\Stress-Tester"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\WangCJ\Codes\Dev Codes\OITools\Stress-Tester"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	D:\Programs\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\Programs\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\WangCJ\Codes\Dev Codes\OITools\Stress-Tester\CMakeFiles" "D:\WangCJ\Codes\Dev Codes\OITools\Stress-Tester\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\WangCJ\Codes\Dev Codes\OITools\Stress-Tester\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oit-stress

# Build rule for target.
oit-stress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 oit-stress
.PHONY : oit-stress

# fast build rule for target.
oit-stress/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/build
.PHONY : oit-stress/fast

#=============================================================================
# Target rules for targets named chk-caseicmp

# Build rule for target.
chk-caseicmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-caseicmp
.PHONY : chk-caseicmp

# fast build rule for target.
chk-caseicmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-caseicmp.dir\build.make checkers/CMakeFiles/chk-caseicmp.dir/build
.PHONY : chk-caseicmp/fast

#=============================================================================
# Target rules for targets named chk-casencmp

# Build rule for target.
chk-casencmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-casencmp
.PHONY : chk-casencmp

# fast build rule for target.
chk-casencmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-casencmp.dir\build.make checkers/CMakeFiles/chk-casencmp.dir/build
.PHONY : chk-casencmp/fast

#=============================================================================
# Target rules for targets named chk-casewcmp

# Build rule for target.
chk-casewcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-casewcmp
.PHONY : chk-casewcmp

# fast build rule for target.
chk-casewcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-casewcmp.dir\build.make checkers/CMakeFiles/chk-casewcmp.dir/build
.PHONY : chk-casewcmp/fast

#=============================================================================
# Target rules for targets named chk-dcmp

# Build rule for target.
chk-dcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-dcmp
.PHONY : chk-dcmp

# fast build rule for target.
chk-dcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-dcmp.dir\build.make checkers/CMakeFiles/chk-dcmp.dir/build
.PHONY : chk-dcmp/fast

#=============================================================================
# Target rules for targets named chk-fcmp

# Build rule for target.
chk-fcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-fcmp
.PHONY : chk-fcmp

# fast build rule for target.
chk-fcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-fcmp.dir\build.make checkers/CMakeFiles/chk-fcmp.dir/build
.PHONY : chk-fcmp/fast

#=============================================================================
# Target rules for targets named chk-hcmp

# Build rule for target.
chk-hcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-hcmp
.PHONY : chk-hcmp

# fast build rule for target.
chk-hcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-hcmp.dir\build.make checkers/CMakeFiles/chk-hcmp.dir/build
.PHONY : chk-hcmp/fast

#=============================================================================
# Target rules for targets named chk-icmp

# Build rule for target.
chk-icmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-icmp
.PHONY : chk-icmp

# fast build rule for target.
chk-icmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-icmp.dir\build.make checkers/CMakeFiles/chk-icmp.dir/build
.PHONY : chk-icmp/fast

#=============================================================================
# Target rules for targets named chk-lcmp

# Build rule for target.
chk-lcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-lcmp
.PHONY : chk-lcmp

# fast build rule for target.
chk-lcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-lcmp.dir\build.make checkers/CMakeFiles/chk-lcmp.dir/build
.PHONY : chk-lcmp/fast

#=============================================================================
# Target rules for targets named chk-ncmp

# Build rule for target.
chk-ncmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-ncmp
.PHONY : chk-ncmp

# fast build rule for target.
chk-ncmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-ncmp.dir\build.make checkers/CMakeFiles/chk-ncmp.dir/build
.PHONY : chk-ncmp/fast

#=============================================================================
# Target rules for targets named chk-nyesno

# Build rule for target.
chk-nyesno: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-nyesno
.PHONY : chk-nyesno

# fast build rule for target.
chk-nyesno/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-nyesno.dir\build.make checkers/CMakeFiles/chk-nyesno.dir/build
.PHONY : chk-nyesno/fast

#=============================================================================
# Target rules for targets named chk-rcmp

# Build rule for target.
chk-rcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-rcmp
.PHONY : chk-rcmp

# fast build rule for target.
chk-rcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-rcmp.dir\build.make checkers/CMakeFiles/chk-rcmp.dir/build
.PHONY : chk-rcmp/fast

#=============================================================================
# Target rules for targets named chk-rcmp4

# Build rule for target.
chk-rcmp4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-rcmp4
.PHONY : chk-rcmp4

# fast build rule for target.
chk-rcmp4/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-rcmp4.dir\build.make checkers/CMakeFiles/chk-rcmp4.dir/build
.PHONY : chk-rcmp4/fast

#=============================================================================
# Target rules for targets named chk-rcmp6

# Build rule for target.
chk-rcmp6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-rcmp6
.PHONY : chk-rcmp6

# fast build rule for target.
chk-rcmp6/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-rcmp6.dir\build.make checkers/CMakeFiles/chk-rcmp6.dir/build
.PHONY : chk-rcmp6/fast

#=============================================================================
# Target rules for targets named chk-rcmp9

# Build rule for target.
chk-rcmp9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-rcmp9
.PHONY : chk-rcmp9

# fast build rule for target.
chk-rcmp9/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-rcmp9.dir\build.make checkers/CMakeFiles/chk-rcmp9.dir/build
.PHONY : chk-rcmp9/fast

#=============================================================================
# Target rules for targets named chk-rncmp

# Build rule for target.
chk-rncmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-rncmp
.PHONY : chk-rncmp

# fast build rule for target.
chk-rncmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-rncmp.dir\build.make checkers/CMakeFiles/chk-rncmp.dir/build
.PHONY : chk-rncmp/fast

#=============================================================================
# Target rules for targets named chk-uncmp

# Build rule for target.
chk-uncmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-uncmp
.PHONY : chk-uncmp

# fast build rule for target.
chk-uncmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-uncmp.dir\build.make checkers/CMakeFiles/chk-uncmp.dir/build
.PHONY : chk-uncmp/fast

#=============================================================================
# Target rules for targets named chk-wcmp

# Build rule for target.
chk-wcmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-wcmp
.PHONY : chk-wcmp

# fast build rule for target.
chk-wcmp/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-wcmp.dir\build.make checkers/CMakeFiles/chk-wcmp.dir/build
.PHONY : chk-wcmp/fast

#=============================================================================
# Target rules for targets named chk-yesno

# Build rule for target.
chk-yesno: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chk-yesno
.PHONY : chk-yesno

# fast build rule for target.
chk-yesno/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\chk-yesno.dir\build.make checkers/CMakeFiles/chk-yesno.dir/build
.PHONY : chk-yesno/fast

#=============================================================================
# Target rules for targets named checkers

# Build rule for target.
checkers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 checkers
.PHONY : checkers

# fast build rule for target.
checkers/fast:
	$(MAKE) $(MAKESILENT) -f checkers\CMakeFiles\checkers.dir\build.make checkers/CMakeFiles/checkers.dir/build
.PHONY : checkers/fast

src/base/runner.obj: src/base/runner.cpp.obj
.PHONY : src/base/runner.obj

# target to build an object file
src/base/runner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/base/runner.cpp.obj
.PHONY : src/base/runner.cpp.obj

src/base/runner.i: src/base/runner.cpp.i
.PHONY : src/base/runner.i

# target to preprocess a source file
src/base/runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/base/runner.cpp.i
.PHONY : src/base/runner.cpp.i

src/base/runner.s: src/base/runner.cpp.s
.PHONY : src/base/runner.s

# target to generate assembly for a file
src/base/runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/base/runner.cpp.s
.PHONY : src/base/runner.cpp.s

src/core/cleaner.obj: src/core/cleaner.cpp.obj
.PHONY : src/core/cleaner.obj

# target to build an object file
src/core/cleaner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/cleaner.cpp.obj
.PHONY : src/core/cleaner.cpp.obj

src/core/cleaner.i: src/core/cleaner.cpp.i
.PHONY : src/core/cleaner.i

# target to preprocess a source file
src/core/cleaner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/cleaner.cpp.i
.PHONY : src/core/cleaner.cpp.i

src/core/cleaner.s: src/core/cleaner.cpp.s
.PHONY : src/core/cleaner.s

# target to generate assembly for a file
src/core/cleaner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/cleaner.cpp.s
.PHONY : src/core/cleaner.cpp.s

src/core/helper.obj: src/core/helper.cpp.obj
.PHONY : src/core/helper.obj

# target to build an object file
src/core/helper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/helper.cpp.obj
.PHONY : src/core/helper.cpp.obj

src/core/helper.i: src/core/helper.cpp.i
.PHONY : src/core/helper.i

# target to preprocess a source file
src/core/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/helper.cpp.i
.PHONY : src/core/helper.cpp.i

src/core/helper.s: src/core/helper.cpp.s
.PHONY : src/core/helper.s

# target to generate assembly for a file
src/core/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/helper.cpp.s
.PHONY : src/core/helper.cpp.s

src/core/options.obj: src/core/options.cpp.obj
.PHONY : src/core/options.obj

# target to build an object file
src/core/options.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/options.cpp.obj
.PHONY : src/core/options.cpp.obj

src/core/options.i: src/core/options.cpp.i
.PHONY : src/core/options.i

# target to preprocess a source file
src/core/options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/options.cpp.i
.PHONY : src/core/options.cpp.i

src/core/options.s: src/core/options.cpp.s
.PHONY : src/core/options.s

# target to generate assembly for a file
src/core/options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/options.cpp.s
.PHONY : src/core/options.cpp.s

src/core/tester.obj: src/core/tester.cpp.obj
.PHONY : src/core/tester.obj

# target to build an object file
src/core/tester.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/tester.cpp.obj
.PHONY : src/core/tester.cpp.obj

src/core/tester.i: src/core/tester.cpp.i
.PHONY : src/core/tester.i

# target to preprocess a source file
src/core/tester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/tester.cpp.i
.PHONY : src/core/tester.cpp.i

src/core/tester.s: src/core/tester.cpp.s
.PHONY : src/core/tester.s

# target to generate assembly for a file
src/core/tester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/core/tester.cpp.s
.PHONY : src/core/tester.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-stress.dir\build.make CMakeFiles/oit-stress.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... checkers
	@echo ... chk-caseicmp
	@echo ... chk-casencmp
	@echo ... chk-casewcmp
	@echo ... chk-dcmp
	@echo ... chk-fcmp
	@echo ... chk-hcmp
	@echo ... chk-icmp
	@echo ... chk-lcmp
	@echo ... chk-ncmp
	@echo ... chk-nyesno
	@echo ... chk-rcmp
	@echo ... chk-rcmp4
	@echo ... chk-rcmp6
	@echo ... chk-rcmp9
	@echo ... chk-rncmp
	@echo ... chk-uncmp
	@echo ... chk-wcmp
	@echo ... chk-yesno
	@echo ... oit-stress
	@echo ... src/base/runner.obj
	@echo ... src/base/runner.i
	@echo ... src/base/runner.s
	@echo ... src/core/cleaner.obj
	@echo ... src/core/cleaner.i
	@echo ... src/core/cleaner.s
	@echo ... src/core/helper.obj
	@echo ... src/core/helper.i
	@echo ... src/core/helper.s
	@echo ... src/core/options.obj
	@echo ... src/core/options.i
	@echo ... src/core/options.s
	@echo ... src/core/tester.obj
	@echo ... src/core/tester.i
	@echo ... src/core/tester.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

